### ISSUE TITLE
Migration issues, cant delete lock / doesnt exist

### ISSUE THREAD

**Issue by qrpike** [docker-library/ghost#122]
I am using docker image 1.20 with mysql as the DB connector. Blog was working fine, it got rescheduled to a new host and now its stuck in a migration error.

```[2018-01-18 06:08:01] ERROR
 NAME: MigrationsAreLockedError
MESSAGE: Migrations are running at the moment. Please wait that the lock get`s released.
 level:normal
 Either the release was never released because of a e.g. died process or a parallel process is migrating at the moment.
If your database looks okay, you can manually release the lock by running `UPDATE migrations_lock set locked=0 where lock_key='km01';`.
MigrationsAreLockedError: Migrations are running at the moment. Please wait that the lock get`s released.
    at MigrationsAreLockedError.KnexMigrateError (/var/lib/ghost/versions/1.20.1/node_modules/knex-migrator/lib/errors.js:9:26)
    at new MigrationsAreLockedError (/var/lib/ghost/versions/1.20.1/node_modules/knex-migrator/lib/errors.js:40:26)
    at /var/lib/ghost/versions/1.20.1/node_modules/knex-migrator/lib/index.js:799:27
    at tryCatcher (/var/lib/ghost/versions/1.20.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.20.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/lib/ghost/versions/1.20.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/1.20.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/1.20.1/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/lib/ghost/versions/1.20.1/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/lib/ghost/versions/1.20.1/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/lib/ghost/versions/1.20.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```
The MySQL database has no entries in either `migrations` or `migrations_lock`. When I enter the container and try to run the knex command with `--force` the error still persists.

**Comment by HADB** [comment]
Same problem

**Comment by pascalandy** [comment]
I had this issue. I simply restored my db.sql and I was fine.
I had no idea what caused this but that what backup are for :-p
