### ISSUE TITLE
update ghost from 1.x to 2.x in docker

### ISSUE THREAD

**Issue by cnjack** [docker-library/ghost#147]
```
docker exec -it blog bash
su node -c "ghost update"
```
bring me some error 
```
Running sudo command: systemctl is-active ghost_undefined
A ProcessError occurred.

Message: Command failed: /bin/sh -c sudo -S -p '#node-sudo-passwd#'  systemctl is-active ghost_undefined
/bin/sh: 1: sudo: not found


Exit code: 127


Debug Information:
    OS: linux, v4.16.0-999-generic
    Node Version: v8.11.4
    Ghost-CLI Version: 1.9.1
    Environment: production
    Command: 'ghost update'

Additional log info available in: /home/node/.ghost/logs/ghost-cli-debug-2018-08-27T06_40_43_725Z.log

Try running ghost doctor to check your system for known issues.

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
```

**Comment by cnjack** [comment]
try 
```
docker exec -u node blog ghost update
```
is not ok

**Comment by cnjack** [comment]
I try to mv sudo to the docker, it is ok
but new error:
```
- Checking for Ghost-CLI updates
Running sudo command: systemctl is-active ghost_undefined
/usr/local/lib/node_modules/ghost-cli/lib/ui/index.js:132
            throw new errors.SystemError('Prompts have been disabled, please provide options via command line flags');
            ^

Error: Prompts have been disabled, please provide options via command line flags
    at UI.prompt (/usr/local/lib/node_modules/ghost-cli/lib/ui/index.js:132:19)
    at Socket.cp.stderr.on (/usr/local/lib/node_modules/ghost-cli/lib/ui/index.js:212:22)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:597:20)
```

**Comment by tianon** [comment]
You _should_ be able to update by simply mounting your old 1.0-based volume on a Ghost 2.0 image (and it should auto-upgrade on first run).  It would probably be prudent for us to add a note about this to the docs.

cc @acburdine (I might be mistaken!)

**Comment by crespum** [comment]
That doesn't work. I don't have the detailed logs here, but it turns out the migration is not happening and the server won't start because the DB is missing the new `comment_id` field.

**Comment by acburdine** [comment]
Hmm...it _should_ work the way @tianon described, but I'll do some testing and check.

**Comment by acburdine** [comment]
@crespum I checked locally and can't reproduce - the ghost v2 image migrates and starts fine when a ghost v1 content folder (using sqlite3 as the db) is mounted into it.

**Comment by crespum** [comment]
That's strange, I've gathered the logs I get (first I pull v2 image, then I stop and remove v1 container and finally I run v2):
```bash
root@debian:~# docker pull ghost
root@debian:~# docker stop ghost-blog
ghost-blog
root@debian:~# docker rm ghost-blog
ghost-blog
root@debian:~# docker run --restart always --name ghost-blog -d -p 6001:2368 -v /home/ghost/ghost-blog:/var/lib/ghost/content ghost
891cc5e9194de27...9cab5087970
root@debian:~# docker logs ghost-blog
[2018-08-29 07:13:12] WARN Theme's file locales/en.json not found. 
[2018-08-29 07:13:13] INFO Blog is in maintenance mode. 
[2018-08-29 07:13:13] INFO Ghost is running in production... 
[2018-08-29 07:13:13] INFO Your blog is now available
[2018-08-29 07:13:13] INFO Ctrl+C to shut down 
[2018-08-29 07:13:13] INFO Ghost boot 4.071s 
[2018-08-29 07:13:13] INFO Creating database backup 
[2018-08-29 07:13:16] INFO Database backup written to: /var/lib/ghost/content/data/blog.ghost.2018-08-29.json 
[2018-08-29 07:13:16] INFO Adding demo post. 
[2018-08-29 07:13:17] INFO Rollback: Fixture posts. 
[2018-08-29 07:13:17] INFO Rollback: Bring back demo post. 
[2018-08-29 07:13:18] ERROR

NAME: RollbackError
CODE: SQLITE_ERROR
MESSAGE: insert into `posts` (`author_id`, `comment_id`, `created_at`, `created_by`, `feature_image`, `featured`, `html`, `id`, `meta_description`, `meta_title`, `mobiledoc`, `page`, `plaintext`, `published_by`, `slug`, `status`, `title`, `updated_at`, `updated_by`, `uuid`, `visibility`) values ('5951f5fca366002ebd5dbef7', '5b86478dcd8f550001a2da47', '2018-08-29 07:13:17', 1, NULL, false, 'Content of demo post', NULL, 'v2-demo-post', 'draft', 'Koenig Demo Post', '2018-08-29 07:13:17', 1, 'c7f6f55d-d619-436a-8e4c-a874bbc67552', 'public') - SQLITE_ERROR: table posts has no column named comment_id

level:normal

OuterError: insert into `posts` (`author_id`, `comment_id`, `created_at`, `created_by`, `custom_excerpt`, `feature_image`, `featured`, `html`, `id`, `meta_description`, `meta_title`, `mobiledoc`, `page`, `plaintext`, `published_at`, `published_by`, `slug`, `status`, `title`, `updated_at`, `updated_by`, `uuid`, `visibility`) values ('1', '5b86478ccd8f550001a2da46', '2018-08-29 07:13:16', 1, 'Content of demo post', NULL, 'v2-demo-post', 'draft', 'Koenig Demo Post', '2018-08-29 07:13:17', 1, 'c7f6f55d-d619-436a-8e4c-a874bbc67552', 'public') - SQLITE_ERROR: table posts has no column named comment_id
    at RollbackError.KnexMigrateError (/var/lib/ghost/versions/2.0.3/node_modules/knex-migrator/lib/errors.js:7:26)
    at new RollbackError (/var/lib/ghost/versions/2.0.3/node_modules/knex-migrator/lib/errors.js:32:26)
    at /var/lib/ghost/versions/2.0.3/node_modules/knex-migrator/lib/index.js:496:23
    at tryCatcher (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

Error: SQLITE_ERROR: table posts has no column named comment_id
```

**Comment by cnjack** [comment]
is done!
1. backup the data dir
2. docker rm -f blog
3. docker run -d --name blog -v ~/data/blog:/var/lib/ghost/content -p2368:2368 ghost:1.25
4. wait the ghost is run...
5. docker rm -f blog
6.  docker run -d --name blog -v ~/data/blog:/var/lib/ghost/content -p2368:2368 ghost

**Comment by crespum** [comment]
That's works. I don't really know what my problem was. I was using v1 before, but the docker image seems to be quite different (250MB smaller)...
```
~# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ghost               1.25                bcd04969a22b        6 days ago          820MB
ghost               latest              1029fdadd2aa        6 days ago          827MB
ghost               <none>              b5529c7678ac        7 months ago        584MB
```

**Comment by BirkhoffLee** [comment]
I too have the same issue as OP's. I'm using docker-compose to deploy the stack, but when I re-pull the `ghost` image (to get a 2.0 image) and re-deploy the stack, bunches of `Error: ER_BAD_FIELD_ERROR: Unknown column 'comment_id' in 'field list'` pops up. Ghost is seemly not migrating the old data and database.

**Comment by cnjack** [comment]
@BirkhoffLee you can Imitate my operation

**Comment by BirkhoffLee** [comment]
@cnjack It didn't work in the first time, I tried it again and it magically worked :) thanks!

**Comment by PhilWhitehurst** [comment]
I too just got this issue.

> Head over to the Ghost 2.0 Theme Compatibility
[https://forum.ghost.org/t/ghost-2-0-theme-compatibility-help-support/2103] 
forum topic to discuss any changes and get help if needed.

That''s it!

We''re looking forward to sharing more about the new editor soon', NULL, 'v2-demo-post', 'draft', 'Koenig Demo Post', '2018-08-30 12:59:24', 1, 'd25e8546-dacd-4352-af3d-cfb39ed8b4f0', 'public') - SQLITE_ERROR: table posts has no column named comment_id
    at RollbackError.KnexMigrateError (/var/lib/ghost/versions/2.0.3/node_modules/knex-migrator/lib/errors.js:7:26)
    at new RollbackError (/var/lib/ghost/versions/2.0.3/node_modules/knex-migrator/lib/errors.js:32:26)
    at /var/lib/ghost/versions/2.0.3/node_modules/knex-migrator/lib/index.js:496:23
    at tryCatcher (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/lib/ghost/versions/2.0.3/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

Error: SQLITE_ERROR: table posts has no column named comment_id

I overcame the issue by

1. Export content under labs menu option in admin panel
2. Stopped ghost-:1-alpine
3. Deleted ghost.db under data
4. Started ghost:alpine (version 2 of ghost) pointing at same volumes as ghost:1-alpine was
5. Went into ghost in browser and setup admin account
6. Import previously exported content
7. Unpublished all the gettng started ghost posts.
8. Flushed any caches (nginx, Cloudflare between ghost on browser)

**Comment by acburdine** [comment]
@PhilWhitehurst Did you by chance try to update to 2.x from a 1.x release < 1.25.4? In Ghost-CLI we added a provision that prevented updates if you were not already running the latest 1.x version of Ghost, and my guess is that the errors you're seeing are related to the fact that you need to upgrade to the latest 1.x version first before trying the 2.x upgrade.

@tianon would it be worth adding a section to the readme noting the above? (I can draft a PR) Since a couple people have run into it already i'd imagine more people might stumble across this.

**Comment by tianon** [comment]
Yeah, sounds like that'd be prudent! 👍

**Comment by PhilWhitehurst** [comment]
@acburdine  @tianon 

Yes the version I was upgrading from was 1.22.7. It had been running in a docker container for 3 months without fail and I had not updated the image to the latest 1.x series.

Loving the new 2.0 editor by the way, very nice implementation of mobileDoc.

**Comment by hyperknot** [comment]
I can confirm that direct update to`2-alpine` didn't work, but doing an `1-alpine` update before fixed it.

**Comment by AlbertoFdzM** [comment]
@acburdine I tried several times:
1. `ghost:1-alpine`
1. `ghost:2-alpine`

With no results until switching to `:1`. Probably I was having some issues cleaning my docker cache.
