### ISSUE TITLE
Problems when using 'pg' as database__client

### ISSUE THREAD

**Issue by ayedo** [docker-library/ghost#188]
Hello,

first of all I would like to thank you for your great work on this docker image!

Unfortunately, I cannot manage to get it running with a "pg" database client. I get the following error:

```
$ npm install pg --save
Error: Cannot find module 'pg'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Client_PG._driver (/var/lib/ghost/versions/2.25.4/node_modules/knex/lib/dialects/postgres/index.js:110:12)
    at Client_PG.initializeDriver (/var/lib/ghost/versions/2.25.4/node_modules/knex/lib/client.js:254:26)
    at Client_PG.Client (/var/lib/ghost/versions/2.25.4/node_modules/knex/lib/client.js:115:10)
    at new Client_PG (/var/lib/ghost/versions/2.25.4/node_modules/knex/lib/dialects/postgres/index.js:72:20)
    at Knex (/var/lib/ghost/versions/2.25.4/node_modules/knex/lib/index.js:60:34)
    at Object.<anonymous> (/var/lib/ghost/versions/2.25.4/core/server/data/db/connection.js:33:20)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
```
I've tried to manually install pg inside the container, like so: `docker exec --it ghost /bin/bash`, and then execute ` npm install pg --save`. There were some warnings, but it seemed to have worked.

There is a post on StackOverflow that suggests that the node_modules folder might not be where it would be expected, but I could not figure out how that could be the case in this dockerfile?

**Comment by ayedo** [comment]
I found out that Postgres is not officially supported anymore. That might be the problem.
