### ISSUE TITLE
Ghost 1.x

### ISSUE THREAD

**Issue by tianon** [docker-library/ghost#203]
We've got a couple issues with Ghost 1.x:

- not EOL yet (to be clear)
- based on Node.js 8 (which is EOL)
- any image rebuild (on Node.js 8 or 10) results in:

```
Knex: run
$ npm install sqlite3 --save
TypeError: Cannot read property 'prototype' of undefined
    at inherits (/var/lib/ghost/versions/1.26.2/node_modules/sqlite3/lib/sqlite3.js:27:16)
    at Object.<anonymous> (/var/lib/ghost/versions/1.26.2/node_modules/sqlite3/lib/sqlite3.js:66:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Client_SQLite3._driver (/var/lib/ghost/versions/1.26.2/node_modules/knex/lib/dialects/sqlite3/index.js:79:12)
    at Client_SQLite3.initializeDriver (/var/lib/ghost/versions/1.26.2/node_modules/knex/lib/client.js:254:26)
    at Client_SQLite3.Client (/var/lib/ghost/versions/1.26.2/node_modules/knex/lib/client.js:115:10)
    at new Client_SQLite3 (/var/lib/ghost/versions/1.26.2/node_modules/knex/lib/dialects/sqlite3/index.js:62:20)
    at Knex (/var/lib/ghost/versions/1.26.2/node_modules/knex/lib/index.js:60:34)
    at Object.connect (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/lib/database.js:23:12)
    at KnexMigrator.init (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/lib/index.js:81:32)
    at KnexMigrator.migrate (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/lib/index.js:335:21)
    at /var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/bin/knex-migrator-migrate:26:29
    at tryCatcher (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/1.26.2/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:649:10)
```

**Comment by wglambert** [comment]
There's 2 unresolved issues on https://github.com/mapbox/node-sqlite3 with this error
https://github.com/mapbox/node-sqlite3/issues/1130
https://github.com/mapbox/node-sqlite3/issues/1185

**Comment by wglambert** [comment]
The error descriptor `at Object.<anonymous> (/var/lib/ghost/versions/1.26.2/node_modules/sqlite3/lib/sqlite3.js:66:1)`
points to the line [`inherits(Backup, EventEmitter);`](https://github.com/mapbox/node-sqlite3/blob/1afb9152780b681ec6eaeeadfe98b0f70b274449/lib/sqlite3.js#L66)

Which was added in https://github.com/mapbox/node-sqlite3/pull/1116

@ggravarr Also mentioned commenting out that line will let it run successfully
https://github.com/mapbox/node-sqlite3/issues/1185#issuecomment-520087073

**Comment by tianon** [comment]
@acburdine any ideas/thoughts?  Should we just drop support for Ghost 1.x?  Should we try to resolve the `sqlite3` issue?

I imagine it either needs a version bump or an explicit version downgrade, but I'll admit I'm definitely out of *my* depth here. :smile:

I'll note that https://ghost.org/faq/major-versions-lts/ talks about "Jan 2020", but I'm not positive whether that's "Jan 1, 2020" or "we'll support Ghost 1.x through Jan, thus Feb 1, 2020"

**Comment by shawntoffel** [comment]
Is this issue also a blocker for the Ghost 3.3.0 release? It appears the update.sh build has been failing.  https://doi-janky.infosiftr.net/job/update.sh/job/ghost/4866/console

**Comment by tianon** [comment]
Yeah, unfortunately our automation can't overcome an issue like that by itself -- I've manually pushed the update in https://github.com/docker-library/ghost/commit/399fc7055104fea391d55b387f031b305ee4ad11 and https://github.com/docker-library/official-images/pull/7275 for now.

**Comment by tianon** [comment]
For the `sqlite3` issue, it appears something is modifying `package.json`.

From https://github.com/TryGhost/Ghost/blob/1.26.2/package.json#L100-L102:

```json
...
  "optionalDependencies": {
    "sqlite3": "4.0.1"
  },
...
```

Inside the image (and the output from `npm view` during build):

```json
...
  "optionalDependencies": {
    "sqlite3": "4.1.1"
  },
...
```
