### ISSUE TITLE
Upgrade to latest ghost docker image 4.46.2 fails

### ISSUE THREAD

**Issue by groundhog2k** [docker-library/ghost#305]
My ghost blog runs on previous available Ghost docker image 4.44.0.
I upgraded to latest available Ghost docker image 4.46.0.
Container fails to startup and I see following error log:

```
[2022-05-03 17:24:55] INFO Database backup written to: /var/lib/ghost/content/data/test.ghost.2022-05-03-17-24-55.json
[2022-05-03 17:24:55] INFO Running migrations.
[2022-05-03 17:24:55] INFO Dropping nullable: newsletters.created_at
[2022-05-03 17:24:55] INFO Rolling back: alter table `newsletters` modify  `created_at` datetime not null default 'NULL' - Invalid default value for 'created_at'.
[2022-05-03 17:24:55] INFO Setting nullable: newsletters.created_at
[2022-05-03 17:24:55] ERROR alter table `newsletters` modify  `created_at` datetime null default 'NULL' - Invalid default value for 'created_at'
alter table `newsletters` modify  `created_at` datetime null default 'NULL' - Invalid default value for 'created_at'
"OuterError: alter table `newsletters` modify  `created_at` datetime not null default 'NULL' - Invalid default value for 'created_at'"
Error ID:
    400
Error Code: 
    ER_INVALID_DEFAULT
----------------------------------------
RollbackError: alter table `newsletters` modify  `created_at` datetime null default 'NULL' - Invalid default value for 'created_at'
    at DatabaseStateManager.makeReady (/var/lib/ghost/versions/4.46.2/core/server/data/db/state-manager.js:95:32)
    at RollbackError.KnexMigrateError (/var/lib/ghost/versions/4.46.2/node_modules/knex-migrator/lib/errors.js:7:26)
    at new RollbackError (/var/lib/ghost/versions/4.46.2/node_modules/knex-migrator/lib/errors.js:31:26)
    at KnexMigrator.migrate (/var/lib/ghost/versions/4.46.2/node_modules/knex-migrator/lib/index.js:418:31)
    at async DatabaseStateManager.makeReady (/var/lib/ghost/versions/4.46.2/core/server/data/db/state-manager.js:86:17)
    at async initDatabase (/var/lib/ghost/versions/4.46.2/core/boot.js:69:5)
    at async bootGhost (/var/lib/ghost/versions/4.46.2/core/boot.js:414:9)
Error: alter table `newsletters` modify  `created_at` datetime null default 'NULL' - Invalid default value for 'created_at'
    at Packet.asError (/var/lib/ghost/versions/4.46.2/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/var/lib/ghost/versions/4.46.2/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/var/lib/ghost/versions/4.46.2/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/var/lib/ghost/versions/4.46.2/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/var/lib/ghost/versions/4.46.2/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/var/lib/ghost/versions/4.46.2/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

I guess it's releated to version jump from Ghost 4.44.x to 4.46.x. But there is no docker image for 4.45.x available?
Any solution to solve the error above?

**Comment by acburdine** [comment]
@groundhog2k this appears to be the same issue as https://github.com/TryGhost/Ghost/issues/14634 - so I'm going to close this issue as it's likely an issue in Ghost itself.

**Comment by nanoamp** [comment]
I used the official Ghost docker-compose file which used to be based on *mariadb*, and now fails to run. I've just migrated it from *mariadb* to *mysql* with the following process. You're welcome to try it. I make no promises or warranties, I might have forgotten something, your backup plans are your own! At each stage, look at the output to make sure it's sane, and follow whatever names and identifiers are used in **your** _docker-compose.yml_ file. Details might be different from mine.

Start by making sure the docker containers are *not* running. Look at the location of the db files in the _docker-compose.yml_ file, via the _volumes_ directive under the _db_ section:

```db:
  db:
    image: mariadb:latest
    volumes:
      - /opt/ghostdb:/var/lib/mysql
  #     ^^^^^^^^^^^^ this is the location you need    
```

Make a complete copy of this folder *somewhere* as a backup. Here, I'm just copying it to my home directory:

```
cp -r /opt/ghostdb ~/ghostdbcopy
```

Start the existing db with:

```
docker-compose up db
```

For me, this creates a container called _docker_db_1_. Use this container name in the following command in a second terminal window, to login to the container:

```
docker exec -it docker_db_1 bash
```

In the resulting container, run the following to dump the database to a file. You'll need to enter the _MYSQL_PASSWORD_ value from your _docker-compose.yml_:

```
mysqldump --opt -Q -u ghostdb -p ghostdb > ~/ghostdb.sql
ls -l ~/ghostdb.sql
```

This should confirm that a dump was created in the root user's home directory. Mine was about 730K in size, yours may well be a bit bigger, or a bit smaller. Exit the _bash_ shell in that container with:

```
exit
```

and you should be back at the host. Copy the dump to the host with:

```
docker cp docker_db_1:/root/ghostdb.sql ~/ghostdb.sql
```

Now you can Ctrl-C to stop the db container in the first window. Edit the _docker-compose.yml_ to replace `mariadb:latest` with `mysql:8.0`. The required db _image_ directive should end up something like the following (although the volume may point to a different location):

```
  db:
    image: mysql:8.0
    volumes:
      - /opt/ghostdb:/var/lib/mysql
```

Go to the location listed in the first half of the volume mapping, and clear it out as follows (if there are mariadb files left, migration to mysql won't work):

```
cd /opt/ghostdb # change this based on what's in your docker-compose.yml
rm -r *
```

Now restart the db container, which will now install and use mysql instead:

```
docker-compose up db
```

It should start up and create an empty ghostdb. In your second terminal window, copy the dump to the new container, and login to it:

```
docker cp ~/ghostdb.sql docker_db_1:/root/ghostdb.sql
docker exec -it docker_db_1 bash
```

In the container, you can now restore the dump (again, you'll need to enter the _MYSQL_PASSWORD_ value from _docker-compose.yml_:

```
mysql -u ghostdb -p ghostdb < ~/ghostdb.sql
exit
```

Once that's completed, you can go back to the first terminal, Ctrl-C to stop the db container, and restart the whole container suite:

```
docker-compose up
```

You should see the migration complete, and ghost start up as it used to.

**Comment by pascalandy** [comment]
I @nanoamp, can you please point to that file ?

> I used the official Ghost docker-compose file

**Comment by nanoamp** [comment]
> Hi @nanoamp, can you please point to that file ?
> 
> > I used the official Ghost docker-compose file

Now I'm looking for evidence of it being official, but I can't find a canonical mariadb-based reference in the docs. I know the docs often change, but I don't know if this is an example of that, or if I just completely misremembered using an off-piste source. Anyway, I've edited my original post.

The closest YAML I can find online today to the file that I originally used is [this](https://techblog.thcb.org/how-to-install-ghost-cms-with-docker-on-ubuntu-20-04/).

**Comment by pascalandy** [comment]
Thank you Sir! I'm looking around as I will have to update to MYSQL 8 soon enough.
