### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by chatofking** [docker-library/ghost#313]
here is mine docker-compose settings

> # by default, the Ghost image will use SQLite (and thus requires no separate database container)
# we have used MySQL here merely for demonstration purposes (especially environment-variable-based configuration)

version: '3.1'

services:

ghost:
image: ghost:5-alpine
restart: always
ports:
- 8080:2368
environment:
# see https://ghost.org/docs/config/#configuration-options
database__client: mysql
database__connection__host: db
database__connection__user: root
database__connection__password: example
database__connection__database: ghost
# this url value is just an example, and is likely wrong for your environment!
url: http://localhost:8080/
# contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly>
#NODE_ENV: development

db:
image: mysql:8.0-oracle
restart: always
environment:
MYSQL_ROOT_PASSWORD: example

i can't conntect http://localhost:8080/
ERR_CONNECTION_REFUSED
 i got this
message
`Creating ghost_ghost_1 ... done
Creating ghost_db_1    ... done
Attaching to ghost_db_1, ghost_ghost_1
db_1     | 2022-06-14 00:15:24+00:00 [Note] [Entrypoint]: Entrypoint script for                                                                               MySQL Server 8.0.29-1.el8 started.
db_1     | 2022-06-14 00:15:29+00:00 [Note] [Entrypoint]: Switching to dedicated                                                                               user 'mysql'
db_1     | 2022-06-14 00:15:29+00:00 [Note] [Entrypoint]: Entrypoint script for                                                                               MySQL Server 8.0.29-1.el8 started.
db_1     | 2022-06-14 00:15:30+00:00 [Note] [Entrypoint]: Initializing database                                                                               files
db_1     | 2022-06-14T00:15:30.510032Z 0 [System] [MY-013169] [Server] /usr/sbin                                                                              /mysqld (mysqld 8.0.29) initializing of server in progress as process 43
db_1     | 2022-06-14T00:15:30.628731Z 1 [System] [MY-013576] [InnoDB] InnoDB in                                                                              itialization has started.
db_1     | 2022-06-14T00:15:42.667519Z 1 [System] [MY-013577] [InnoDB] InnoDB in                                                                              itialization has ended.
ghost_1  | [2022-06-14 00:15:53] INFO Ghost is running in production...
ghost_1  | [2022-06-14 00:15:53] INFO Your site is now available on http://local                                                                              host:8080/
ghost_1  | [2022-06-14 00:15:53] INFO Ctrl+C to shut down
ghost_1  | [2022-06-14 00:15:54] INFO Ghost server started in 24.171s
ghost_1  | [2022-06-14 00:15:56] ERROR connect ECONNREFUSED 172.18.0.3:3306
ghost_1  |
ghost_1  | connect ECONNREFUSED 172.18.0.3:3306
ghost_1  |
ghost_1  | "Unknown database error"
ghost_1  |
ghost_1  | Error ID:
ghost_1  |     500
ghost_1  |
ghost_1  | Error Code:
ghost_1  |     ECONNREFUSED
ghost_1  |
ghost_1  | ----------------------------------------
ghost_1  |
ghost_1  | Error: connect ECONNREFUSED 172.18.0.3:3306
ghost_1  |     at /var/lib/ghost/versions/5.2.2/node_modules/knex-migrator/lib/d                                                                              atabase.js:57:19
ghost_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
ghost_1  |
ghost_1  | [2022-06-14 00:15:56] WARN Ghost is shutting down
ghost_1  | [2022-06-14 00:15:56] WARN Ghost has shut down
ghost_1  | [2022-06-14 00:15:56] WARN Your site is now offline
ghost_1  | [2022-06-14 00:15:56] WARN Ghost was running for a few seconds
db_1     | 2022-06-14T00:15:58.159875Z 6 [Warning] [MY-010453] [Server] root@loc                                                                              alhost is created with an empty password ! Please consider switching off the --i                                                                              nitialize-insecure option.
db_1     | 2022-06-14 00:16:43+00:00 [Note] [Entrypoint]: Database files initialized
db_1     | 2022-06-14 00:16:43+00:00 [Note] [Entrypoint]: Starting temporary server
db_1     | 2022-06-14T00:16:52.673671Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.29) starting as process 92
db_1     | 2022-06-14T00:16:56.035457Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
ghost_1  | [2022-06-14 00:16:56] INFO Ghost is running in production...
ghost_1  | [2022-06-14 00:16:59] INFO Your site is now available on http://localhost:8080/
ghost_1  | [2022-06-14 00:16:59] INFO Ctrl+C to shut down
ghost_1  | [2022-06-14 00:17:03] INFO Ghost server started in 29.734s
db_1     | 2022-06-14T00:17:08.756837Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
ghost_1  | [2022-06-14 00:17:17] ERROR connect ECONNREFUSED 172.18.0.3:3306
ghost_1  |
ghost_1  | connect ECONNREFUSED 172.18.0.3:3306
ghost_1  |
ghost_1  | "Unknown database error"
ghost_1  |
ghost_1  | Error ID:
ghost_1  |     500
ghost_1  |
ghost_1  | Error Code:
ghost_1  |     ECONNREFUSED
ghost_1  |
ghost_1  | ----------------------------------------
ghost_1  |
ghost_1  | Error: connect ECONNREFUSED 172.18.0.3:3306
ghost_1  |     at /var/lib/ghost/versions/5.2.2/node_modules/knex-migrator/lib/database.js:57:19
ghost_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
ghost_1  |
ghost_1  | [2022-06-14 00:17:18] WARN Ghost is shutting down
ghost_1  | [2022-06-14 00:17:18] WARN Ghost has shut down
ghost_1  | [2022-06-14 00:17:18] WARN Your site is now offline
ghost_1  | [2022-06-14 00:17:18] WARN Ghost was running for a minute
db_1     | 2022-06-14T00:17:18.776014Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1     | 2022-06-14T00:17:18.776376Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
db_1     | 2022-06-14T00:17:19.617885Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
db_1     | 2022-06-14T00:17:19.618463Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
db_1     | 2022-06-14 00:17:24+00:00 [Note] [Entrypoint]: Temporary server started.
db_1     | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
ghost_ghost_1 exited with code 2
db_1     | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
db_1     | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
db_1     | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone.                                                                               Skipping it.
db_1     | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone.                                                                               Skipping it.
db_1     | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zo                                                                              ne. Skipping it.
db_1     |
db_1     | 2022-06-14 00:18:11+00:00 [Note] [Entrypoint]: Stopping temporary ser                                                                              ver
db_1     | 2022-06-14T00:18:12.138239Z 10 [System] [MY-013172] [Server] Received                                                                               SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.29).
ghost_1  | [2022-06-14 00:18:17] INFO Ghost is running in production...
ghost_1  | [2022-06-14 00:18:17] INFO Your site is now available on http://localhost:8080/
ghost_1  | [2022-06-14 00:18:17] INFO Ctrl+C to shut down
ghost_1  | [2022-06-14 00:18:17] INFO Ghost server started in 15.654s
ghost_1  | [2022-06-14 00:18:20] ERROR connect ECONNREFUSED 172.18.0.3:3306
ghost_1  |
ghost_1  | connect ECONNREFUSED 172.18.0.3:3306
ghost_1  |
ghost_1  | "Unknown database error"
ghost_1  |
ghost_1  | Error ID:
ghost_1  |     500
ghost_1  |
ghost_1  | Error Code:
ghost_1  |     ECONNREFUSED
ghost_1  |
ghost_1  | ----------------------------------------
ghost_1  |
ghost_1  | Error: connect ECONNREFUSED 172.18.0.3:3306
ghost_1  |     at /var/lib/ghost/versions/5.2.2/node_modules/knex-migrator/lib/database.js:57:19
ghost_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
ghost_1  |
ghost_1  | [2022-06-14 00:18:20] WARN Ghost is shutting down
ghost_1  | [2022-06-14 00:18:20] WARN Ghost has shut down
ghost_1  | [2022-06-14 00:18:20] WARN Your site is now offline
ghost_1  | [2022-06-14 00:18:20] WARN Ghost was running for a few seconds
ghost_ghost_1 exited with code 2
db_1     | 2022-06-14T00:18:30.441223Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.29)  MySQL Community Server - GPL.
db_1     | 2022-06-14 00:18:31+00:00 [Note] [Entrypoint]: Temporary server stopped
db_1     |
db_1     | 2022-06-14 00:18:31+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
db_1     |
db_1     | 2022-06-14T00:18:49.633892Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.29) starting as process 1
db_1     | 2022-06-14T00:18:52.968974Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db_1     | 2022-06-14T00:19:02.625345Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
db_1     | 2022-06-14T00:19:13.233656Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1     | 2022-06-14T00:19:13.234070Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
db_1     | 2022-06-14T00:19:14.770177Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
db_1     | 2022-06-14T00:19:14.778483Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
ghost_1  | [2022-06-14 00:19:28] INFO Ghost is running in production...
ghost_1  | [2022-06-14 00:19:28] INFO Your site is now available on http://localhost:8080/
ghost_1  | [2022-06-14 00:19:28] INFO Ctrl+C to shut down
ghost_1  | [2022-06-14 00:19:28] INFO Ghost server started in 11.876s
ghost_1  | [2022-06-14 00:19:31] WARN Database state requires initialisation.
ghost_1  | [2022-06-14 00:19:40] INFO Creating table: newsletters
ghost_1  | [2022-06-14 00:19:41] INFO Creating table: posts
ghost_1  | [2022-06-14 00:19:42] INFO Creating table: posts_meta
ghost_1  | [2022-06-14 00:19:43] INFO Creating table: users
ghost_1  | [2022-06-14 00:19:44] INFO Creating table: posts_authors
ghost_1  | [2022-06-14 00:19:45] INFO Creating table: roles
ghost_1  | [2022-06-14 00:19:45] INFO Creating table: roles_users
ghost_1  | [2022-06-14 00:19:45] INFO Creating table: permissions
ghost_1  | [2022-06-14 00:19:46] INFO Creating table: permissions_users
ghost_1  | [2022-06-14 00:19:46] INFO Creating table: permissions_roles
ghost_1  | [2022-06-14 00:19:46] INFO Creating table: settings
ghost_1  | [2022-06-14 00:19:46] INFO Creating table: tags
ghost_1  | [2022-06-14 00:19:47] INFO Creating table: posts_tags
ghost_1  | [2022-06-14 00:19:48] INFO Creating table: invites
ghost_1  | [2022-06-14 00:19:48] INFO Creating table: brute
ghost_1  | [2022-06-14 00:19:48] INFO Creating table: sessions
ghost_1  | [2022-06-14 00:19:49] INFO Creating table: integrations
ghost_1  | [2022-06-14 00:19:49] INFO Creating table: webhooks
ghost_1  | [2022-06-14 00:19:50] INFO Creating table: api_keys
ghost_1  | [2022-06-14 00:19:50] INFO Creating table: mobiledoc_revisions
ghost_1  | [2022-06-14 00:19:51] INFO Creating table: members
ghost_1  | [2022-06-14 00:19:51] INFO Creating table: products
ghost_1  | [2022-06-14 00:19:51] INFO Creating table: offers
ghost_1  | [2022-06-14 00:19:53] INFO Creating table: benefits
ghost_1  | [2022-06-14 00:19:53] INFO Creating table: products_benefits
ghost_1  | [2022-06-14 00:19:55] INFO Creating table: members_products
ghost_1  | [2022-06-14 00:19:57] INFO Creating table: posts_products
ghost_1  | [2022-06-14 00:19:57] INFO Creating table: members_cancel_events
ghost_1  | [2022-06-14 00:19:58] INFO Creating table: members_payment_events
ghost_1  | [2022-06-14 00:19:58] INFO Creating table: members_login_events
ghost_1  | [2022-06-14 00:19:59] INFO Creating table: members_email_change_events
ghost_1  | [2022-06-14 00:19:59] INFO Creating table: members_status_events
ghost_1  | [2022-06-14 00:20:00] INFO Creating table: members_product_events
ghost_1  | [2022-06-14 00:20:02] INFO Creating table: members_paid_subscription_events
ghost_1  | [2022-06-14 00:20:02] INFO Creating table: labels
ghost_1  | [2022-06-14 00:20:03] INFO Creating table: members_labels
ghost_1  | [2022-06-14 00:20:03] INFO Creating table: members_stripe_customers
ghost_1  | [2022-06-14 00:20:04] INFO Creating table: members_stripe_customers_subscriptions
ghost_1  | [2022-06-14 00:20:06] INFO Creating table: offer_redemptions
ghost_1  | [2022-06-14 00:20:07] INFO Creating table: members_subscribe_events
ghost_1  | [2022-06-14 00:20:09] INFO Creating table: stripe_products
ghost_1  | [2022-06-14 00:20:09] INFO Creating table: stripe_prices
ghost_1  | [2022-06-14 00:20:10] INFO Creating table: actions
ghost_1  | [2022-06-14 00:20:10] INFO Creating table: emails
ghost_1  | [2022-06-14 00:20:11] INFO Creating table: email_batches
ghost_1  | [2022-06-14 00:20:11] INFO Creating table: email_recipients
ghost_1  | [2022-06-14 00:20:14] INFO Creating table: tokens
ghost_1  | [2022-06-14 00:20:15] INFO Creating table: snippets
ghost_1  | [2022-06-14 00:20:15] INFO Creating table: custom_theme_settings
ghost_1  | [2022-06-14 00:20:15] INFO Creating table: members_newsletters
ghost_1  | [2022-06-14 00:20:20] INFO Model: Product
ghost_1  | [2022-06-14 00:20:20] INFO Model: Newsletter
ghost_1  | [2022-06-14 00:20:20] INFO Model: Tag
ghost_1  | [2022-06-14 00:20:20] INFO Model: Permission
ghost_1  | [2022-06-14 00:20:24] INFO Model: Post
ghost_1  | [2022-06-14 00:20:33] INFO Model: Integration
ghost_1  | [2022-06-14 00:20:33] INFO Relation: Role to Permission
ghost_1  | [2022-06-14 00:20:37] INFO Relation: Post to Tag
ghost_1  | [2022-06-14 00:20:38] INFO Database is in a ready state.
ghost_1  | Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
ghost_1  | [2022-06-14 00:20:38] INFO Ghost database ready in 81.768s
ghost_1  | Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
ghost_1  | Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
ghost_1  | Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
ghost_1  | Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
ghost_1  | Ignoring invalid configuration option passed to Connection: filename. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
ghost_1  | [2022-06-14 00:21:04] INFO Ghost URL Service Ready in 107.385s
ghost_1  | [2022-06-14 00:21:07] INFO Stripe not configured - skipping migrations
ghost_1  | [2022-06-14 00:21:07] INFO Ghost booted in 110.941s
ghost_1  | [2022-06-14 00:21:07] INFO Adding offloaded job to the queue
ghost_1  | [2022-06-14 00:21:07] INFO Scheduling job update-check at 48 7 8 * * *. Next run on: Tue Jun 14 2022 08:07:48 GMT+0000 (Coordinated Universal Time)`

**Comment by wglambert** [comment]
The connection was unstable at the start while the containers were brought up. At the end it output `INFO Database is in a ready state.` so it should be fully initialized, and going to the ghost url at localhost:8080 should work fine
