### ISSUE TITLE
Site can’t be reached in development mode

### ISSUE THREAD

**Issue by vekerdyb** [docker-library/ghost#88]
When I run `docker run --rm --name some-ghost ghost` and go to `http://localhost:2368/`, I can see the site working fine.

But if I run `docker run --rm --name some-ghost --env NODE_ENV=development ghost`, the site is not available at `http://localhost:2368`.

Log output:
```
[2017-09-05 08:48:10] INFO Creating table: posts 
[2017-09-05 08:48:10] INFO Creating table: users 
[2017-09-05 08:48:10] INFO Creating table: roles 
[2017-09-05 08:48:10] INFO Creating table: roles_users 
[2017-09-05 08:48:10] INFO Creating table: permissions 
[2017-09-05 08:48:10] INFO Creating table: permissions_users 
[2017-09-05 08:48:10] INFO Creating table: permissions_roles 
[2017-09-05 08:48:10] INFO Creating table: permissions_apps 
[2017-09-05 08:48:10] INFO Creating table: settings 
[2017-09-05 08:48:10] INFO Creating table: tags 
[2017-09-05 08:48:10] INFO Creating table: posts_tags 
[2017-09-05 08:48:10] INFO Creating table: apps 
[2017-09-05 08:48:10] INFO Creating table: app_settings 
[2017-09-05 08:48:10] INFO Creating table: app_fields 
[2017-09-05 08:48:10] INFO Creating table: clients 
[2017-09-05 08:48:10] INFO Creating table: client_trusted_domains 
[2017-09-05 08:48:10] INFO Creating table: accesstokens 
[2017-09-05 08:48:10] INFO Creating table: refreshtokens 
[2017-09-05 08:48:10] INFO Creating table: subscribers 
[2017-09-05 08:48:10] INFO Creating table: invites 
[2017-09-05 08:48:10] INFO Creating table: brute 
[2017-09-05 08:48:10] INFO Model: Post 
[2017-09-05 08:48:10] INFO Model: Tag 
[2017-09-05 08:48:10] INFO Model: Client 
[2017-09-05 08:48:10] INFO Model: Role 
[2017-09-05 08:48:10] INFO Model: Permission 
[2017-09-05 08:48:11] INFO Model: User 
[2017-09-05 08:48:11] INFO Relation: Role to Permission 
[2017-09-05 08:48:11] INFO Relation: Post to Tag 
[2017-09-05 08:48:11] INFO Relation: User to Role 
[2017-09-05 08:48:12] INFO Finished database migration! 
(node:1) Warning: a promise was created in a handler at var/lib/ghost/versions/1.8.1/core/server/index.js:86:14 but was not returned from it, see http://goo.gl/rRqMUw
    at .fetch (/var/lib/ghost/versions/1.8.1/node_modules/bluebird/js/release/method.js:13:13)
[2017-09-05 08:48:17] INFO Ghost is running in development... 
[2017-09-05 08:48:17] INFO Listening on: 127.0.0.1:2368 
[2017-09-05 08:48:17] INFO Url configured as: http://localhost:2368/ 
[2017-09-05 08:48:17] INFO Ctrl+C to shut down 
[2017-09-05 08:48:17] INFO Ghost boot 4.073s 
```
That warning seems to come from the `auth.init` promise handler.

Am I missing some configuration? Is this documented somewhere? 
Thanks!

**Comment by acburdine** [comment]
@vekerdyb Hey! So that warning is normal and can be ignored. However, the reason your setup isn't working when you run Ghost in development mode is that configuration for Ghost in 1.0 is done on a per-environment basis, as opposed to pre-1.0 Ghost where everything was in one config file. Because of this change, the docker image only creates a production config.

That being said, it is possible to configure Ghost using environment variables (see [the docs](disabled={{not availableAddressTypes.length}})). So, if you really _must_ run Ghost in development mode, you should be able to do it with this command:

```sh
docker run --rm --name some-ghost --env NODE_ENV=development --env server__host=0.0.0.0 --env url="http://localhost:2368" ghost
```

The important part of that command is the server host - by default ghost listens on 127.0.0.1, but because of how docker manages ports, you'll need to make it listen on 0.0.0.0 to accept connections correctly.

Closing this as it's possible to configure things with environment variables.
