### ISSUE TITLE
armhf: npm install sqlite3 runs into an error

### ISSUE THREAD

**Issue by Siassei** [docker-library/ghost#98]
Creating a fresh docker container fails on an armv7l plattform. The error occurs due to an well documented issue with sqlite on armhf plattforms. But my programming skills are not good enough to solve the prolbem :(

My Plattform: Raspberry Pi 3, Debain 
`Linux raspberrypi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux`
The docker-compose.yml
```yaml
version: '3'

services:
  ghost:
    container_name: ghost-1
    image: ghost:1
    restart: always
    ports:
      - "127.0.0.1:2368:2368"
    volumes:
      - "ghost-data:/var/lib/ghost/content"

volumes:
  ghost-data:
```
running compose
```console
# docker-compose up
Creating volume "ghost_ghost-data" with default driver
Creating ghost-1 ... 
Creating ghost-1 ... done
Attaching to ghost-1
ghost-1  | Knex: run
ghost-1  | $ npm install sqlite3 --save
ghost-1  | Error: Cannot find module 'sqlite3'
ghost-1  |     at Function.Module._resolveFilename (module.js:469:15)
ghost-1  |     at Function.Module._load (module.js:417:25)
ghost-1  |     at Module.require (module.js:497:17)
ghost-1  |     at require (internal/module.js:20:19)
ghost-1  |     at Client_SQLite3._driver (/usr/local/lib/node_modules/knex-migrator/node_modules/knex/lib/dialects/sqlite3/index.js:75:12)
ghost-1  |     at Client_SQLite3.initializeDriver (/usr/local/lib/node_modules/knex-migrator/node_modules/knex/lib/client.js:219:26)
ghost-1  |     at Client_SQLite3.Client (/usr/local/lib/node_modules/knex-migrator/node_modules/knex/lib/client.js:113:10)
ghost-1  |     at new Client_SQLite3 (/usr/local/lib/node_modules/knex-migrator/node_modules/knex/lib/dialects/sqlite3/index.js:58:20)
ghost-1  |     at Knex (/usr/local/lib/node_modules/knex-migrator/node_modules/knex/lib/index.js:60:34)
ghost-1  |     at Object.connect (/usr/local/lib/node_modules/knex-migrator/lib/database.js:25:12)
ghost-1  |     at KnexMigrator.init (/usr/local/lib/node_modules/knex-migrator/lib/index.js:71:32)
ghost-1  |     at KnexMigrator.migrate (/usr/local/lib/node_modules/knex-migrator/lib/index.js:161:21)
ghost-1  |     at /usr/local/lib/node_modules/knex-migrator/bin/knex-migrator-migrate:26:29
ghost-1  |     at tryCatcher (/usr/local/lib/node_modules/knex-migrator/node_modules/bluebird/js/release/util.js:16:23)
ghost-1  |     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:512:31)
ghost-1  |     at Promise._settlePromise (/usr/local/lib/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:569:18)
ghost-1  |     at Promise._settlePromise0 (/usr/local/lib/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:614:10)
ghost-1  |     at Promise._settlePromises (/usr/local/lib/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:693:18)
ghost-1  |     at Promise._fulfill (/usr/local/lib/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:638:18)
ghost-1  |     at Promise._resolveCallback (/usr/local/lib/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:432:57)
ghost-1  |     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:524:17)
ghost-1  |     at Promise._settlePromise (/usr/local/lib/node_modules/knex-migrator/node_modules/bluebird/js/release/promise.js:569:18)
ghost-1 exited with code 1
```

**Comment by AlejandroCabeza** [comment]
I've also come across this issue. I started the container with bash instead of the default entry point and executed it step by step. It seems the error is being caused due to missing the _content/logs_ folder.

**Comment by tianon** [comment]
Good catch!  I've filed https://github.com/docker-library/ghost/pull/101 which fixes this. :+1:

**Comment by tianon** [comment]
(Realized my comment might be unintentionally trivializing the amount of work it was to find/fix the root of the issue -- @yosifkit can attest that he and I spent hours together pouring over this problem to find a solution that actually works properly and with minimal hankering.)
